# -*- coding: utf-8 -*-
"""Prakash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJ8c7eKN5iPlteB5G1SmVzv8VmgmYQbP
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

BASE_URL = "https://www.amazon.in"
SEARCH_TERM = "bags"
PAGES_TO_SCRAPE = 2

def get_product_data(product_div):
    product_link = product_div.find("a", class_="a-link-normal")
    if product_link:
        product_url = BASE_URL + product_link["href"]
    else:
        product_url = "N/A"

    product_name_element = product_div.find("span", class_="a-text-normal")
    if product_name_element:
        product_name = product_name_element.get_text(strip=True)
    else:
        product_name = "N/A"

    product_price_element = product_div.find("span", class_="a-price-whole")
    if product_price_element:
        product_price = product_price_element.get_text(strip=True)
    else:
        product_price = "N/A"

    product_rating_element = product_div.find("span", class_="a-icon-alt")
    if product_rating_element:
        product_rating = product_rating_element.get_text(strip=True)
    else:
        product_rating = "N/A"

    num_reviews_element = product_div.find("span", class_="a-size-base")
    if num_reviews_element:
        num_reviews = num_reviews_element.get_text(strip=True)
    else:
        num_reviews = "N/A"

    return {
        "url": product_url,
        "name": product_name,
        "price": product_price,
        "rating": product_rating,
        "reviews": num_reviews,
    }

def scrape_amazon_products():
    all_products = []

    for page in range(1, PAGES_TO_SCRAPE + 1):
        url = f"https://www.amazon.in/s?k={SEARCH_TERM}&page={page}"
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")
        product_divs = soup.find_all("div", class_="s-result-item")

        for product_div in product_divs:
            product_data = get_product_data(product_div)
            all_products.append(product_data)

    return all_products

products = scrape_amazon_products()
df = pd.DataFrame(products)
df.head()